[book]
authors = ["Taiyoh Network", "xDrHellx", "shenef", "Raphi", "Drakodan"]
language = "en"
src = "src"
title = "Boktai Speedrunning"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/shenef/Boktai-Speedrunning"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/shenef/Boktai-Speedrunning/edit/main/{path}"

# CSS and JS files are imported in the order they are listed here!
# pagetoc.css, pagetoc.js and index.hbs by https://github.com/JorelAli/mdBook-pagetoc
additional-css = [
    "./theme/css/colors.css",
    "./theme/css/tables.css",
    "./theme/css/misc.css",
]

additional-js = [
    "./theme/js/papaparse.min.js",
]

# currently incompatible
# [output.linkcheck]
# optional = true
